import { TipoMateria } from '../contenido/entities/contenido.entity';

export const DEFAULT_UNIT_QUIZZES = [
  {
    unidadId: 1,
    tipoMateria: TipoMateria.COMPILADORES,
    titulo: 'Quiz Unidad I - Introducción',
    descripcion: 'Repaso de objetivos, evaluación y panorama general del curso.',
    publicado: true,
    preguntas: [
      {
        orden: 1,
        enunciado: '¿Cuál es el propósito principal de la materia de compiladores dentro del curso?',
        opciones: [
          'Comprender y construir etapas de traducción para un lenguaje formal',
          'Aprender únicamente sintaxis de Java',
          'Administrar redes de computadoras',
          'Diseñar interfaces gráficas comerciales',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La unidad introduce el diseño de compiladores como un proceso de traducción y construcción formal.',
      },
      {
        orden: 2,
        enunciado: '¿Qué caracteriza a la evaluación planteada en el curso?',
        opciones: [
          'Se basa en participación, ejercicios y proyecto por etapas',
          'Sólo considera un examen final',
          'Únicamente acepta tareas escritas a mano',
          'Se limita a asistencia sin productos',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'Desde la introducción se presenta un esquema con trabajo continuo y proyecto progresivo.',
      },
      {
        orden: 3,
        enunciado: '¿Qué enfoque general se espera del estudiante al iniciar el curso?',
        opciones: [
          'Relacionar teoría formal con implementación práctica',
          'Memorizar comandos sin analizarlos',
          'Evitar el uso de modelos formales',
          'Trabajar sólo con ejemplos no computacionales',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La materia conecta conceptos formales con analizadores y traductores reales.',
      },
    ],
  },
  {
    unidadId: 2,
    tipoMateria: TipoMateria.COMPILADORES,
    titulo: 'Quiz Unidad II - Traductores',
    descripcion: 'Conceptos base de traductores, compiladores e intérpretes.',
    publicado: true,
    preguntas: [
      {
        orden: 1,
        enunciado: '¿Qué hace un traductor en el contexto de lenguajes de programación?',
        opciones: [
          'Convierte una representación de entrada a otra representación equivalente',
          'Sólo ejecuta instrucciones en tiempo real sin analizarlas',
          'Borra errores de sintaxis automáticamente',
          'Sustituye por completo la necesidad de un lenguaje formal',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'Un traductor transforma programas o cadenas de un lenguaje fuente a otro destino.',
      },
      {
        orden: 2,
        enunciado: '¿Cuál es una diferencia clásica entre compilador e intérprete?',
        opciones: [
          'El compilador traduce antes de ejecutar y el intérprete analiza mientras ejecuta',
          'El intérprete siempre genera código máquina permanente',
          'El compilador nunca detecta errores',
          'No existe diferencia funcional entre ambos',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La distinción principal está en cuándo y cómo se realiza la traducción.',
      },
      {
        orden: 3,
        enunciado: '¿Por qué los sistemas de traducción son fundamentales?',
        opciones: [
          'Porque permiten la comunicación entre especificaciones humanas y la máquina',
          'Porque sustituyen la lógica del hardware',
          'Porque eliminan el uso de alfabetos y gramáticas',
          'Porque impiden el análisis semántico',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'El curso enfatiza que son esenciales para comunicar instrucciones comprensibles a la computadora.',
      },
      {
        orden: 4,
        enunciado: 'Didacmax 2000 se menciona como:',
        opciones: [
          'Un compilador didáctico con instrucciones en español',
          'Un sistema operativo de red',
          'Una base de datos relacional',
          'Un lenguaje de marcas para la web',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'El material lo presenta como un compilador didáctico eficiente y retador.',
      },
    ],
  },
  {
    unidadId: 3,
    tipoMateria: TipoMateria.COMPILADORES,
    titulo: 'Quiz Unidad III - Lenguajes',
    descripcion: 'Lenguajes formales, símbolos, alfabetos y reglas de formación.',
    publicado: true,
    preguntas: [
      {
        orden: 1,
        enunciado: 'En teoría de lenguajes, un alfabeto es:',
        opciones: [
          'Un conjunto finito de símbolos válidos',
          'Una lista de programas ejecutables',
          'Un compilador especializado',
          'Una tabla de variables semánticas',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'El alfabeto es la base para construir cadenas y lenguajes formales.',
      },
      {
        orden: 2,
        enunciado: 'Una cadena en un lenguaje formal se forma a partir de:',
        opciones: [
          'La concatenación de símbolos del alfabeto',
          'Únicamente números enteros',
          'Estados finales de un autómata exclusivamente',
          'Direcciones de memoria físicas',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'Las cadenas son secuencias construidas con símbolos permitidos por el alfabeto.',
      },
      {
        orden: 3,
        enunciado: '¿Qué define a un lenguaje formal frente a un lenguaje natural?',
        opciones: [
          'Sus reglas están descritas de manera precisa y no ambigua',
          'Se usa sólo para conversar oralmente',
          'No puede representarse con gramáticas',
          'Siempre tiene significado coloquial',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La precisión formal es clave para poder analizar y traducir cadenas computacionalmente.',
      },
    ],
  },
  {
    unidadId: 4,
    tipoMateria: TipoMateria.COMPILADORES,
    titulo: 'Quiz Unidad IV - El compilador',
    descripcion: 'Estructura y fases principales del compilador.',
    publicado: true,
    preguntas: [
      {
        orden: 1,
        enunciado: '¿Cuál es una visión correcta del compilador?',
        opciones: [
          'Es un sistema compuesto por varias fases de análisis y traducción',
          'Es sólo un editor de texto técnico',
          'Es únicamente una tabla de símbolos',
          'Es una red neuronal sin reglas formales',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La unidad presenta al compilador como una arquitectura de fases relacionadas.',
      },
      {
        orden: 2,
        enunciado: '¿Qué fase suele transformar caracteres en tokens?',
        opciones: [
          'Análisis léxico',
          'Optimización final exclusivamente',
          'Planificación de memoria externa',
          'Recuperación de contraseña',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'El análisis léxico identifica lexemas y genera tokens para etapas posteriores.',
      },
      {
        orden: 3,
        enunciado: 'La tabla de símbolos sirve principalmente para:',
        opciones: [
          'Concentrar información relevante de identificadores y atributos',
          'Reemplazar la gramática del lenguaje',
          'Dibujar autómatas automáticamente',
          'Eliminar por completo la semántica',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'Es una estructura central para almacenar atributos necesarios durante la compilación.',
      },
      {
        orden: 4,
        enunciado: '¿Por qué las fases del compilador se estudian por separado?',
        opciones: [
          'Porque cada una resuelve un problema distinto del proceso total',
          'Porque no se relacionan entre sí',
          'Porque sólo existe una fase útil',
          'Porque se ejecutan en diferentes computadoras obligatoriamente',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La separación permite comprender responsabilidades y dependencias entre fases.',
      },
    ],
  },
  {
    unidadId: 5,
    tipoMateria: TipoMateria.COMPILADORES,
    titulo: 'Quiz Unidad V - Análisis Léxico',
    descripcion: 'Tokens, patrones, lexemas y reconocimiento léxico.',
    publicado: true,
    preguntas: [
      {
        orden: 1,
        enunciado: 'Un token representa:',
        opciones: [
          'Una categoría léxica reconocida por el analizador',
          'Una computadora completa',
          'Un error lógico del usuario',
          'Una fase de optimización',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'El token abstrae el tipo de lexema detectado en la entrada.',
      },
      {
        orden: 2,
        enunciado: '¿Qué relación existe entre un patrón y un lexema?',
        opciones: [
          'El patrón describe la forma y el lexema es la ocurrencia concreta',
          'El lexema describe la regla y el patrón es el compilador',
          'No guardan relación',
          'Ambos son siempre estados finales',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'El patrón especifica la forma válida; el lexema es el fragmento real encontrado.',
      },
      {
        orden: 3,
        enunciado: 'Las expresiones regulares se usan en análisis léxico porque:',
        opciones: [
          'Permiten describir formalmente clases de cadenas',
          'Sustituyen al parser sintáctico',
          'Evitan reconocer identificadores',
          'Funcionan sólo con gráficos',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'Son una herramienta formal natural para especificar tokens.',
      },
      {
        orden: 4,
        enunciado: '¿Qué debe hacer un analizador léxico ante una secuencia inválida?',
        opciones: [
          'Detectar y reportar el error con base en las reglas del alfabeto y patrones',
          'Aceptar cualquier símbolo sin validarlo',
          'Modificar la gramática del lenguaje',
          'Ignorar de forma permanente la entrada restante',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'El manejo de errores es parte del trabajo del analizador léxico.',
      },
    ],
  },
  {
    unidadId: 6,
    tipoMateria: TipoMateria.COMPILADORES,
    titulo: 'Quiz Unidad VI - Análisis Sintáctico',
    descripcion: 'Parsing, gramáticas y validación estructural.',
    publicado: true,
    preguntas: [
      {
        orden: 1,
        enunciado: 'El análisis sintáctico verifica principalmente:',
        opciones: [
          'La estructura de los tokens según una gramática',
          'El color del editor',
          'La velocidad de internet',
          'Sólo el tamaño del archivo fuente',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'El parser valida si la secuencia de tokens cumple las reglas sintácticas.',
      },
      {
        orden: 2,
        enunciado: '¿Qué suele construir un parser como representación del programa?',
        opciones: [
          'Un árbol de derivación o estructura sintáctica equivalente',
          'Un cable de comunicación',
          'Una base de datos completa',
          'Un sistema operativo nuevo',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La estructura arbórea ayuda a representar la organización gramatical del código.',
      },
      {
        orden: 3,
        enunciado: 'Cuando una cadena no puede derivarse con la gramática, el parser debe:',
        opciones: [
          'Reportar un error sintáctico',
          'Convertirla en token válido automáticamente',
          'Ignorar la gramática definida',
          'Cambiar el alfabeto del lenguaje sin control',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La imposibilidad de derivación indica una falla en la estructura de la entrada.',
      },
    ],
  },
  {
    unidadId: 7,
    tipoMateria: TipoMateria.COMPILADORES,
    titulo: 'Quiz Unidad VII - Análisis Semántico',
    descripcion: 'Reglas de significado, tipos y consistencia.',
    publicado: true,
    preguntas: [
      {
        orden: 1,
        enunciado: 'El análisis semántico busca asegurar que:',
        opciones: [
          'Las construcciones sintácticamente válidas también tengan sentido en el lenguaje',
          'Todos los programas sean idénticos',
          'La entrada sólo use letras mayúsculas',
          'La compilación omita tipos y contextos',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La semántica valida consistencia de tipos, declaraciones y uso correcto.',
      },
      {
        orden: 2,
        enunciado: '¿Qué ejemplo corresponde a un error semántico?',
        opciones: [
          'Usar una variable no declarada o con tipo incompatible',
          'Tener espacios en blanco entre tokens',
          'Abrir un archivo PDF',
          'Cambiar el nombre del curso',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La semántica revisa el significado y contexto de los elementos del programa.',
      },
      {
        orden: 3,
        enunciado: 'La tabla de símbolos vuelve a ser importante en esta fase porque:',
        opciones: [
          'Permite consultar atributos como tipo, alcance o declaración previa',
          'Sirve sólo para almacenar videos',
          'Evita el uso de reglas semánticas',
          'Sustituye por completo al código intermedio',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'Muchas verificaciones semánticas dependen de atributos guardados en la tabla.',
      },
      {
        orden: 4,
        enunciado: '¿Qué relación existe entre semántica y sintaxis?',
        opciones: [
          'La semántica se aplica sobre estructuras ya aceptadas por la sintaxis',
          'La semántica reemplaza el análisis léxico',
          'La sintaxis depende de la velocidad del hardware',
          'No guardan relación en un compilador',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'Primero debe existir estructura válida para luego revisar su significado.',
      },
    ],
  },
  {
    unidadId: 8,
    tipoMateria: TipoMateria.COMPILADORES,
    titulo: 'Quiz Unidad VIII - Proyecto',
    descripcion: 'Aplicación integradora de conceptos del curso.',
    publicado: true,
    preguntas: [
      {
        orden: 1,
        enunciado: '¿Qué se espera del proyecto final de compiladores?',
        opciones: [
          'Integrar diseño formal, documentación y evidencia funcional',
          'Entregar únicamente una portada sin desarrollo',
          'Memorizar definiciones sin implementación',
          'Presentar sólo un video sin soporte técnico',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La unidad de proyecto integra especificación, pruebas y funcionamiento.',
      },
      {
        orden: 2,
        enunciado: 'La documentación del proyecto debe incluir al menos:',
        opciones: [
          'Descripción técnica, instalación, uso y evidencias de ejecución',
          'Sólo nombres de integrantes',
          'Únicamente bibliografía sin producto',
          'Una lista de comandos sin contexto',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'El material pide documentación formal y pruebas de funcionamiento.',
      },
      {
        orden: 3,
        enunciado: '¿Por qué el proyecto se revisa por etapas?',
        opciones: [
          'Para asegurar avances, retroalimentación y corrección progresiva',
          'Porque no existe relación entre teoría y práctica',
          'Porque sólo la última entrega importa',
          'Para evitar pruebas parciales',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'Las revisiones parciales permiten mejorar el resultado final y sostener el aprendizaje.',
      },
    ],
  },
  {
    unidadId: 1,
    tipoMateria: TipoMateria.TEORIA_DE_LA_COMPUTACION,
    titulo: 'Quiz Unidad I - Bases teóricas',
    descripcion: 'Sistemas formales, conjuntos y fundamentos para compiladores.',
    publicado: true,
    preguntas: [
      {
        orden: 1,
        enunciado: 'Un sistema formal se entiende como:',
        opciones: [
          'Un conjunto de elementos y reglas bien definidas para operar simbólicamente',
          'Una colección aleatoria de programas sin reglas',
          'Un dispositivo físico exclusivamente electrónico',
          'Un compilador terminado listo para producción',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La unidad inicia con la definición formal de sistemas y sus reglas de operación.',
      },
      {
        orden: 2,
        enunciado: 'La teoría de conjuntos aporta al curso porque permite:',
        opciones: [
          'Describir relaciones, elementos y operaciones con precisión',
          'Reemplazar todas las gramáticas',
          'Evitar el uso de símbolos',
          'Ignorar la organización de alfabetos',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'Es base para hablar de alfabetos, lenguajes, relaciones y estructuras formales.',
      },
      {
        orden: 3,
        enunciado: '¿Qué propiedad se asocia a decidir si una afirmación puede resolverse formalmente?',
        opciones: [
          'Decidibilidad',
          'Latencia',
          'Conectividad',
          'Escalabilidad visual',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La decidibilidad es una de las propiedades clásicas estudiadas en sistemas formales.',
      },
    ],
  },
  {
    unidadId: 2,
    tipoMateria: TipoMateria.TEORIA_DE_LA_COMPUTACION,
    titulo: 'Quiz Unidad II - Autómatas Finitos',
    descripcion: 'Estados, transiciones y reconocimiento de lenguajes regulares.',
    publicado: true,
    preguntas: [
      {
        orden: 1,
        enunciado: 'Un autómata finito se compone de estados, alfabeto y:',
        opciones: [
          'Una función de transición y estados de aceptación',
          'Sólo un archivo ejecutable',
          'Una memoria infinita tipo pila obligatoria',
          'Un compilador semántico integrado',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La definición formal incluye estados, alfabeto, transiciones, inicio y aceptación.',
      },
      {
        orden: 2,
        enunciado: '¿Qué caracteriza a un AFD respecto de un AFND?',
        opciones: [
          'Para cada símbolo y estado tiene una única transición posible',
          'Siempre tiene más estados finales',
          'No puede reconocer lenguajes regulares',
          'No utiliza alfabeto',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La determinación implica unicidad en la transición para cada par estado-símbolo.',
      },
      {
        orden: 3,
        enunciado: 'Las expresiones regulares se relacionan con autómatas finitos porque:',
        opciones: [
          'Ambos describen lenguajes regulares y pueden transformarse entre sí',
          'Sólo sirven para bases de datos',
          'Eliminan la noción de estado',
          'No pueden convivir en un mismo curso',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La equivalencia entre ER y autómatas es uno de los ejes de la unidad.',
      },
      {
        orden: 4,
        enunciado: '¿Qué representa normalmente un estado final?',
        opciones: [
          'Una condición de aceptación para la cadena procesada',
          'Un error de compilación irreversible',
          'La última línea de código fuente',
          'El cierre del sistema operativo',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'Si la cadena termina en un estado final, el autómata la acepta.',
      },
    ],
  },
  {
    unidadId: 3,
    tipoMateria: TipoMateria.TEORIA_DE_LA_COMPUTACION,
    titulo: 'Quiz Unidad III - Analizador Léxico',
    descripcion: 'Construcción de analizadores léxicos a partir de reglas formales.',
    publicado: true,
    preguntas: [
      {
        orden: 1,
        enunciado: '¿Qué produce el analizador léxico como salida natural?',
        opciones: [
          'Tokens listos para el análisis sintáctico',
          'Gramáticas normalizadas completas',
          'Estados finales de una pila',
          'Consultas SQL optimizadas',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'Su función central es tokenizar la entrada.',
      },
      {
        orden: 2,
        enunciado: 'El reconocimiento de identificadores suele apoyarse en:',
        opciones: [
          'Patrones definidos con expresiones regulares y autómatas',
          'Sólo imágenes del teclado',
          'Reglas semánticas de tipos',
          'Tablas de presentación oral',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'El analizador léxico emplea descripciones regulares para reconocer clases de cadenas.',
      },
      {
        orden: 3,
        enunciado: '¿Qué papel tiene el manejador de errores léxicos?',
        opciones: [
          'Detectar símbolos o cadenas que no cumplen los patrones válidos',
          'Cambiar automáticamente la gramática del lenguaje',
          'Traducir a código objeto',
          'Asignar calificaciones al alumno',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'Debe identificar entradas inválidas en la fase léxica.',
      },
      {
        orden: 4,
        enunciado: 'La tabla de símbolos en esta unidad ayuda a:',
        opciones: [
          'Registrar lexemas e información asociada para fases posteriores',
          'Reemplazar las transiciones del autómata',
          'Crear videos de aprendizaje',
          'Guardar únicamente calificaciones del curso',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La información léxica útil se conserva para análisis posteriores.',
      },
    ],
  },
  {
    unidadId: 4,
    tipoMateria: TipoMateria.TEORIA_DE_LA_COMPUTACION,
    titulo: 'Quiz Unidad IV - Normalización de Gramáticas',
    descripcion: 'Transformaciones y formas normales de gramáticas.',
    publicado: true,
    preguntas: [
      {
        orden: 1,
        enunciado: 'Normalizar una gramática significa principalmente:',
        opciones: [
          'Transformarla sin cambiar el lenguaje que genera',
          'Eliminar por completo sus producciones',
          'Traducirla a lenguaje máquina',
          'Volverla un archivo gráfico',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La equivalencia del lenguaje debe mantenerse durante la transformación.',
      },
      {
        orden: 2,
        enunciado: '¿Por qué se eliminan ciertas producciones o recursiones problemáticas?',
        opciones: [
          'Para facilitar el análisis y la implementación del parser',
          'Para impedir toda derivación posible',
          'Porque una gramática normalizada no usa no terminales',
          'Para sustituir el alfabeto original',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'Las transformaciones buscan gramáticas más manejables para análisis formal y programación.',
      },
      {
        orden: 3,
        enunciado: 'Una gramática equivalente después de normalizar debe:',
        opciones: [
          'Generar el mismo lenguaje que la original',
          'Aceptar menos cadenas de forma arbitraria',
          'Cambiar todos los terminales',
          'Eliminar las reglas iniciales obligatoriamente',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La equivalencia del lenguaje es el criterio principal de corrección.',
      },
    ],
  },
  {
    unidadId: 5,
    tipoMateria: TipoMateria.TEORIA_DE_LA_COMPUTACION,
    titulo: 'Quiz Unidad V - Analizador Sintáctico',
    descripcion: 'Diseño e implementación de parsers con apoyo de teoría formal.',
    publicado: true,
    preguntas: [
      {
        orden: 1,
        enunciado: '¿Qué requiere un analizador sintáctico para operar correctamente?',
        opciones: [
          'Una gramática bien definida y tokens de entrada válidos',
          'Sólo un compilador optimizador final',
          'Una base de datos externa obligatoria',
          'Un alfabeto sin reglas de producción',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'El parser depende tanto de la gramática como de la tokenización previa.',
      },
      {
        orden: 2,
        enunciado: 'Herramientas como generadores de parser son útiles porque:',
        opciones: [
          'Automatizan parte de la construcción del analizador sintáctico',
          'Eliminan la necesidad de gramáticas',
          'Sustituyen al análisis léxico por completo',
          'Sólo producen interfaces gráficas',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La automatización ayuda a construir analizadores más consistentes y mantenibles.',
      },
      {
        orden: 3,
        enunciado: 'En el análisis sintáctico, un árbol ayuda a:',
        opciones: [
          'Representar la jerarquía y derivación de la entrada',
          'Guardar archivos multimedia',
          'Sustituir todas las reglas semánticas',
          'Evitar el uso de tokens',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'El árbol organiza la estructura derivada a partir de la gramática.',
      },
      {
        orden: 4,
        enunciado: 'La implementación del parser en esta unidad busca que el alumno:',
        opciones: [
          'Conecte la teoría formal con una solución programada funcional',
          'Memorice siglas sin aplicarlas',
          'Trabaje sólo con ejemplos no formales',
          'Ignore las transformaciones gramaticales previas',
        ],
        respuestaCorrectaIndex: 0,
        explicacion: 'La unidad cierra el ciclo entre formalización y construcción real del analizador.',
      },
    ],
  },
];
