-- CreateEnum
CREATE TYPE "TipoMateria" AS ENUM ('COMPILADORES', 'TEORIA_DE_LA_COMPUTACION', 'TEORIA_DE_LENGUAJES');

-- AlterTable
ALTER TABLE "Contenido" ADD COLUMN "tipoMateria" "TipoMateria" NOT NULL DEFAULT 'COMPILADORES';
